// ─── Districts (районы / tumanlar) per UZ region ─────────────────────────────
// Keyed by the region key from MARKET_REGIONS (lib/market-attributes). Each entry
// is a tuple [key, ru, uz]; English reuses the Uzbek (latin) name. Labels are
// resolved at render time via districtLabel() / getDistrictOptions().

import type { Locale } from './translations';

type District = [key: string, ru: string, uz: string];

const DISTRICTS: Record<string, District[]> = {
  tashkent_city: [
    ['bektemir', 'Бектемирский', 'Bektemir'],
    ['chilonzor', 'Чиланзарский', 'Chilonzor'],
    ['yashnobod', 'Яшнабадский', 'Yashnobod'],
    ['mirobod', 'Мирабадский', 'Mirobod'],
    ['mirzo_ulugbek', 'Мирзо-Улугбекский', "Mirzo Ulug'bek"],
    ['sergeli', 'Сергелийский', 'Sergeli'],
    ['olmazor', 'Алмазарский', 'Olmazor'],
    ['uchtepa', 'Учтепинский', 'Uchtepa'],
    ['shayxontohur', 'Шайхантахурский', 'Shayxontohur'],
    ['yakkasaroy', 'Яккасарайский', 'Yakkasaroy'],
    ['yunusobod', 'Юнусабадский', 'Yunusobod'],
    ['yangihayot', 'Янгихаётский', 'Yangihayot'],
  ],
  tashkent_region: [
    ['bekobod', 'Бекабадский', 'Bekobod'],
    ['boka', 'Букинский', "Bo'ka"],
    ['bostonliq', 'Бостанлыкский', "Bo'stonliq"],
    ['chinoz', 'Чиназский', 'Chinoz'],
    ['qibray', 'Кибрайский', 'Qibray'],
    ['ohangaron', 'Ахангаранский', 'Ohangaron'],
    ['oqqorgon', 'Аккурганский', "Oqqo'rg'on"],
    ['parkent', 'Паркентский', 'Parkent'],
    ['piskent', 'Пскентский', 'Piskent'],
    ['quyichirchiq', 'Куйичирчикский', 'Quyichirchiq'],
    ['ortachirchiq', 'Уртачирчикский', "O'rtachirchiq"],
    ['yangiyol', 'Янгиюльский', "Yangiyo'l"],
    ['yuqorichirchiq', 'Юкоричирчикский', 'Yuqorichirchiq'],
    ['zangiota', 'Зангиатинский', 'Zangiota'],
    ['toshkent', 'Ташкентский', 'Toshkent'],
  ],
  andijan: [
    ['andijon', 'Андижанский', 'Andijon'],
    ['asaka', 'Асакинский', 'Asaka'],
    ['baliqchi', 'Балыкчинский', 'Baliqchi'],
    ['buloqboshi', 'Булакбашинский', 'Buloqboshi'],
    ['boston', 'Бустанский', "Bo'ston"],
    ['izboskan', 'Избасканский', 'Izboskan'],
    ['jalaquduq', 'Джалакудукский', 'Jalaquduq'],
    ['xojaobod', 'Ходжаабадский', "Xo'jaobod"],
    ['qorgontepa', 'Кургантепинский', "Qo'rg'ontepa"],
    ['marhamat', 'Мархаматский', 'Marhamat'],
    ['oltinkol', 'Алтынкульский', "Oltinko'l"],
    ['paxtaobod', 'Пахтаабадский', 'Paxtaobod'],
    ['shahrixon', 'Шахриханский', 'Shahrixon'],
    ['ulugnor', 'Улугнорский', "Ulug'nor"],
  ],
  bukhara: [
    ['buxoro', 'Бухарский', 'Buxoro'],
    ['gijduvon', 'Гиждуванский', "G'ijduvon"],
    ['jondor', 'Жондорский', 'Jondor'],
    ['kogon', 'Каганский', 'Kogon'],
    ['olot', 'Алатский', 'Olot'],
    ['peshku', 'Пешкунский', 'Peshku'],
    ['qorakol', 'Каракульский', "Qorako'l"],
    ['qorovulbozor', 'Караулбазарский', 'Qorovulbozor'],
    ['romitan', 'Ромитанский', 'Romitan'],
    ['shofirkon', 'Шафирканский', 'Shofirkon'],
    ['vobkent', 'Вабкентский', 'Vobkent'],
  ],
  fergana: [
    ['fargona', 'Ферганский', "Farg'ona"],
    ['beshariq', 'Бешарыкский', 'Beshariq'],
    ['bogdod', 'Багдадский', "Bag'dod"],
    ['buvayda', 'Бувайдинский', 'Buvayda'],
    ['dangara', 'Дангаринский', "Dang'ara"],
    ['furqat', 'Фуркатский', 'Furqat'],
    ['quva', 'Кувинский', 'Quva'],
    ['qoshtepa', 'Куштепинский', "Qo'shtepa"],
    ['rishton', 'Риштанский', 'Rishton'],
    ['sox', 'Сохский', "So'x"],
    ['toshloq', 'Ташлакский', 'Toshloq'],
    ['uchkoprik', 'Учкуприкский', "Uchko'prik"],
    ['yozyovon', 'Язъяванский', 'Yozyovon'],
    ['oltiariq', 'Алтыарыкский', 'Oltiariq'],
    ['uzbekiston', 'Узбекистанский', "O'zbekiston"],
  ],
  jizzakh: [
    ['jizzax', 'Джизакский', 'Jizzax'],
    ['arnasoy', 'Арнасайский', 'Arnasoy'],
    ['baxmal', 'Бахмальский', 'Baxmal'],
    ['dostlik', 'Дустликский', "Do'stlik"],
    ['forish', 'Фаришский', 'Forish'],
    ['gallaorol', 'Галляаральский', "G'allaorol"],
    ['mirzachol', 'Мирзачульский', "Mirzacho'l"],
    ['paxtakor', 'Пахтакорский', 'Paxtakor'],
    ['yangiobod', 'Янгиабадский', 'Yangiobod'],
    ['zarbdor', 'Зарбдарский', 'Zarbdor'],
    ['zafarobod', 'Зафарабадский', 'Zafarobod'],
    ['zomin', 'Зааминский', 'Zomin'],
    ['sharof_rashidov', 'Шараф-Рашидовский', 'Sharof Rashidov'],
  ],
  namangan: [
    ['namangan', 'Наманганский', 'Namangan'],
    ['chortoq', 'Чартакский', 'Chortoq'],
    ['chust', 'Чустский', 'Chust'],
    ['kosonsoy', 'Касансайский', 'Kosonsoy'],
    ['mingbuloq', 'Мингбулакский', 'Mingbuloq'],
    ['norin', 'Нарынский', 'Norin'],
    ['pop', 'Папский', 'Pop'],
    ['toraqorgon', 'Туракурганский', "To'raqo'rg'on"],
    ['uchqorgon', 'Учкурганский', "Uchqo'rg'on"],
    ['uychi', 'Уйчинский', 'Uychi'],
    ['yangiqorgon', 'Янгикурганский', "Yangiqo'rg'on"],
    ['davlatobod', 'Давлатабадский', 'Davlatobod'],
  ],
  navoi: [
    ['navoiy', 'Навоийский', 'Navoiy'],
    ['karmana', 'Карманинский', 'Karmana'],
    ['konimex', 'Канимехский', 'Konimex'],
    ['navbahor', 'Навбахорский', 'Navbahor'],
    ['nurota', 'Нуратинский', 'Nurota'],
    ['qiziltepa', 'Кызылтепинский', 'Qiziltepa'],
    ['tomdi', 'Тамдынский', 'Tomdi'],
    ['uchquduq', 'Учкудукский', 'Uchquduq'],
    ['xatirchi', 'Хатырчинский', 'Xatirchi'],
  ],
  kashkadarya: [
    ['qarshi', 'Каршинский', 'Qarshi'],
    ['chiroqchi', 'Чиракчинский', 'Chiroqchi'],
    ['dehqonobod', 'Дехканабадский', 'Dehqonobod'],
    ['guzor', 'Гузарский', "G'uzor"],
    ['qamashi', 'Камашинский', 'Qamashi'],
    ['qasbi', 'Касбинский', 'Qasbi'],
    ['koson', 'Касанский', 'Koson'],
    ['kitob', 'Китабский', 'Kitob'],
    ['mirishkor', 'Миришкорский', 'Mirishkor'],
    ['muborak', 'Мубарекский', 'Muborak'],
    ['nishon', 'Нишанский', 'Nishon'],
    ['shahrisabz', 'Шахрисабзский', 'Shahrisabz'],
    ['yakkabog', 'Яккабагский', "Yakkabog'"],
    ['koson_shahar', 'Кукдалинский', "Ko'kdala"],
  ],
  samarkand: [
    ['samarqand', 'Самаркандский', 'Samarqand'],
    ['bulungur', 'Булунгурский', "Bulung'ur"],
    ['ishtixon', 'Иштыханский', 'Ishtixon'],
    ['jomboy', 'Джамбайский', 'Jomboy'],
    ['kattaqorgon', 'Каттакурганский', "Kattaqo'rg'on"],
    ['qoshrabot', 'Кушрабатский', "Qo'shrabot"],
    ['narpay', 'Нарпайский', 'Narpay'],
    ['nurobod', 'Нурабадский', 'Nurobod'],
    ['oqdaryo', 'Акдарьинский', 'Oqdaryo'],
    ['pastdargom', 'Пастдаргомский', "Pastdarg'om"],
    ['paxtachi', 'Пахтачийский', 'Paxtachi'],
    ['payariq', 'Пайарыкский', 'Payariq'],
    ['toyloq', 'Тайлакский', 'Toyloq'],
    ['urgut', 'Ургутский', 'Urgut'],
  ],
  sirdarya: [
    ['guliston', 'Гулистанский', 'Guliston'],
    ['boyovut', 'Баяутский', 'Boyovut'],
    ['sayxunobod', 'Сайхунабадский', 'Sayxunobod'],
    ['sardoba', 'Сардобинский', 'Sardoba'],
    ['mirzaobod', 'Мирзаабадский', 'Mirzaobod'],
    ['oqoltin', 'Акалтынский', 'Oqoltin'],
    ['sirdaryo', 'Сырдарьинский', 'Sirdaryo'],
    ['xovos', 'Хавастский', 'Xovos'],
    ['yangiyer', 'Янгиерский', 'Yangiyer'],
  ],
  surkhandarya: [
    ['termiz', 'Термезский', 'Termiz'],
    ['angor', 'Ангорский', 'Angor'],
    ['bandixon', 'Бандиханский', 'Bandixon'],
    ['boysun', 'Байсунский', 'Boysun'],
    ['denov', 'Денауский', 'Denov'],
    ['jarqorgon', 'Джаркурганский', "Jarqo'rg'on"],
    ['qiziriq', 'Кызырыкский', 'Qiziriq'],
    ['qumqorgon', 'Кумкурганский', "Qumqo'rg'on"],
    ['muzrabot', 'Музрабатский', 'Muzrabot'],
    ['oltinsoy', 'Алтынсайский', 'Oltinsoy'],
    ['sariosiyo', 'Сариасийский', 'Sariosiyo'],
    ['sherobod', 'Шерабадский', 'Sherobod'],
    ['shorchi', 'Шурчинский', "Sho'rchi"],
    ['uzun', 'Узунский', 'Uzun'],
  ],
  khorezm: [
    ['urganch', 'Ургенчский', 'Urganch'],
    ['bogot', 'Багатский', "Bog'ot"],
    ['gurlan', 'Гурленский', 'Gurlan'],
    ['xonqa', 'Ханкинский', 'Xonqa'],
    ['hazorasp', 'Хазараспский', 'Hazorasp'],
    ['xiva', 'Хивинский', 'Xiva'],
    ['qoshkopir', 'Кошкупырский', "Qo'shko'pir"],
    ['shovot', 'Шаватский', 'Shovot'],
    ['yangiariq', 'Янгиарыкский', 'Yangiariq'],
    ['yangibozor', 'Янгибазарский', 'Yangibozor'],
    ['tuproqqala', 'Тупроккалинский', "Tuproqqal'a"],
  ],
  karakalpakstan: [
    ['nukus', 'Нукусский', 'Nukus'],
    ['amudaryo', 'Амударьинский', 'Amudaryo'],
    ['beruniy', 'Берунийский', 'Beruniy'],
    ['chimboy', 'Чимбайский', 'Chimboy'],
    ['ellikqala', 'Элликкалинский', "Ellikqal'a"],
    ['kegeyli', 'Кегейлийский', 'Kegeyli'],
    ['moynoq', 'Муйнакский', "Mo'ynoq"],
    ['qonlikol', 'Канлыкульский', "Qonliko'l"],
    ['qoraozak', 'Караузякский', "Qorao'zak"],
    ['qongirot', 'Кунградский', "Qo'ng'irot"],
    ['shumanay', 'Шуманайский', 'Shumanay'],
    ['taxtakopir', 'Тахтакупырский', "Taxtako'pir"],
    ['tortkol', 'Турткульский', "To'rtko'l"],
    ['xojayli', 'Ходжейлийский', 'Xojayli'],
    ['bozatov', 'Бозатауский', "Bo'zatov"],
  ],
};

export interface DistrictOption {
  value: string;
  label: string;
}

export function getDistrictOptions(region: string | undefined, locale: Locale): DistrictOption[] {
  if (!region) return [];
  return (DISTRICTS[region] ?? []).map(([key, ru, uz]) => ({
    value: key,
    label: locale === 'ru' ? ru : uz,
  }));
}

export function districtLabel(region: string | undefined, key: string | undefined, locale: Locale): string {
  if (!region || !key) return '';
  const found = (DISTRICTS[region] ?? []).find(([k]) => k === key);
  if (!found) return '';
  return locale === 'ru' ? found[1] : found[2];
}
